import * as Yoga$dReact$dDOM$dHTML$dDiv from "../Yoga.React.DOM.HTML.Div/index.js";
import * as Yoga$dReact$dDOM$dHTML$dLi from "../Yoga.React.DOM.HTML.Li/index.js";
import * as Yoga$dReact$dDOM$dHTML$dUl from "../Yoga.React.DOM.HTML.Ul/index.js";
import * as Yoga$dReact$dDOM$dInternal from "../Yoga.React.DOM.Internal/index.js";
const timelineVertical = () => Yoga$dReact$dDOM$dHTML$dUl.ul()()({className: "timeline timeline-vertical"});
const timelineStart = () => Yoga$dReact$dDOM$dHTML$dDiv.div()()({className: "timeline-start"});
const timelineMiddle = () => Yoga$dReact$dDOM$dHTML$dDiv.div()()({className: "timeline-middle"});
const timelineLine = /* #__PURE__ */ Yoga$dReact$dDOM$dInternal.createElementNoKidsImpl("hr", {});
const timelineItem = () => Yoga$dReact$dDOM$dHTML$dLi.li()()({});
const timelineEnd = () => Yoga$dReact$dDOM$dHTML$dDiv.div()()({className: "timeline-end"});
const timeline = () => Yoga$dReact$dDOM$dHTML$dUl.ul()()({className: "timeline"});
export {timeline, timelineEnd, timelineItem, timelineLine, timelineMiddle, timelineStart, timelineVertical};
