import * as Effect$dUncurried from "../Effect.Uncurried/index.js";
import * as Yoga$dReact$dDOM$dHTML$dDiv from "../Yoga.React.DOM.HTML.Div/index.js";
import {closeImpl, showModalImpl} from "./foreign.js";
const showModal = /* #__PURE__ */ Effect$dUncurried.runEffectFn1(showModalImpl);
const modalTop = () => Yoga$dReact$dDOM$dHTML$dDiv.div()()({className: "modal-top"});
const modalMiddle = () => Yoga$dReact$dDOM$dHTML$dDiv.div()()({className: "modal-middle"});
const modalBox = () => Yoga$dReact$dDOM$dHTML$dDiv.div()()({className: "modal-box"});
const modalBottom = () => Yoga$dReact$dDOM$dHTML$dDiv.div()()({className: "modal-bottom"});
const modalBackdrop = "modal-backdrop";
const modalAction = () => Yoga$dReact$dDOM$dHTML$dDiv.div()()({className: "modal-action"});
const closeModal = /* #__PURE__ */ Effect$dUncurried.runEffectFn1(closeImpl);
export {closeModal, modalAction, modalBackdrop, modalBottom, modalBox, modalMiddle, modalTop, showModal};
export * from "./foreign.js";
