import * as Yoga$dReact$dDOM$dHTML$dDiv from "../Yoga.React.DOM.HTML.Div/index.js";
import * as Yoga$dReact$dDOM$dHTML$dUl from "../Yoga.React.DOM.HTML.Ul/index.js";
const top = "dropdown-top";
const right = "dropdown-right";
const open = "dropdown-open";
const left = "dropdown-left";
const hover = "dropdown-hover";
const end = "dropdown-end";
const dropdownContent = () => Yoga$dReact$dDOM$dHTML$dUl.ul()()({className: "dropdown-content menu bg-base-100 rounded-box z-10 w-52 p-2 shadow-sm", tabIndex: 0});
const dropdown = position => () => Yoga$dReact$dDOM$dHTML$dDiv.div()()({className: "dropdown " + position});
const bottom = "dropdown-bottom";
export {bottom, dropdown, dropdownContent, end, hover, left, open, right, top};
