import * as Yoga$dReact$dDOM$dHTML$dSpan from "../Yoga.React.DOM.HTML.Span/index.js";
const xs = "badge-xs";
const warning = "badge-warning";
const success = "badge-success";
const soft = "badge-soft";
const sm = "badge-sm";
const secondary = "badge-secondary";
const primary = "badge-primary";
const outline = "badge-outline";
const neutral = "badge-neutral";
const md = "badge-md";
const lg = "badge-lg";
const info = "badge-info";
const ghost = "badge-ghost";
const error = "badge-error";
const dash = "badge-dash";
const badge = color => size => () => Yoga$dReact$dDOM$dHTML$dSpan.span()()({className: "badge " + color + " " + size});
const accent = "badge-accent";
export {accent, badge, dash, error, ghost, info, lg, md, neutral, outline, primary, secondary, sm, soft, success, warning, xs};
