import * as Yoga$dReact$dDOM$dHTML$dLi from "../Yoga.React.DOM.HTML.Li/index.js";
import * as Yoga$dReact$dDOM$dHTML$dUl from "../Yoga.React.DOM.HTML.Ul/index.js";
const warning = "step-warning";
const vertical = "steps-vertical";
const success = "step-success";
const steps = direction => () => Yoga$dReact$dDOM$dHTML$dUl.ul()()({className: "steps " + direction});
const step = color => () => Yoga$dReact$dDOM$dHTML$dLi.li()()({className: "step " + color});
const secondary = "step-secondary";
const primary = "step-primary";
const neutral = "step-neutral";
const info = "step-info";
const horizontal = "steps-horizontal";
const error = "step-error";
const accent = "step-accent";
export {accent, error, horizontal, info, neutral, primary, secondary, step, steps, success, vertical, warning};
